config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('olymp_007/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp'))
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp.views import index

app_name = 'mainapp'

urlpatterns = [
    # path('ajax/load-maktab/', load_maktab, name='ajax_load_maktab'),
    # path('check/<slug:slug>', check, name='check'),
    # path('check/', check, name='check'),
    path('', index, name="index" ),
]

mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.html import mark_safe

from django.core.files.base import ContentFile
from io import BytesIO
import qrcode

import uuid

User = get_user_model()

TURI_CHOICES = (
        ('trud', 'TRUD(РКИ)'),
        ('dictant', 'Диктант')
    )

STATUS_CHOICES = (
    ('active', 'Active'),
    ('inactive', 'Inactive'),
    ('delete', 'Deleted'))

SINF_CHOICES = (
    ('11-sinf', '11-sinf'),
    ('2-kurs', '2-kurs'),
    )

LANG_CHOICES = (
        ('uz', 'O\'zbek'),
        ('ru', 'Rus'),
    )


class ActiveManager(models.Manager):
	def get_queryset(self):
		return super().get_queryset().filter(status='active')

class Fanlar(models.Model):
    title = models.CharField(max_length=100, verbose_name="Fan nomi")
    creator_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="fan_create", verbose_name="Xodim")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")
    updated = models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active', verbose_name="Holati")
    objects = models.Manager()
    active = ActiveManager()

    def shundan(self):
        students = Students.objects.filter(fan=self.pk).count()
        return students
    
    def umumiy(self):
        return Students.objects.count()
    
    def ru(self):
        return Students.objects.filter(lang='ru', fan=self.pk).count()
    
    def uz(self):
        return Students.objects.filter(lang='uz', fan=self.pk).count()
    
    def __str__(self):
        return f'{self.title}'
    
class Viloyat(models.Model):
    title = models.CharField(max_length=100, verbose_name="Viloyat")
    creator_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="viloyat_create", verbose_name="Xodim")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")
    updated = models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active', verbose_name="Holati")
    objects = models.Manager()
    active = ActiveManager()

    def __str__(self):
        return f'{self.title}'

class Tuman(models.Model):
    vil = models.ForeignKey(Viloyat, on_delete=models.CASCADE, verbose_name="Viloyat")
    title = models.CharField(max_length=100, verbose_name="Tuman")
    creator_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tuman_create", verbose_name="Xodim")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")
    updated = models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active', verbose_name="Holati")
    objects = models.Manager()
    active = ActiveManager()

    def __str__(self):
        return f'{self.title}'
    
    def shundan(self):
        return Students.objects.filter(tuman=self.pk).count()
    shundan.short_description = "Shundan"

    def jami(self):
        students = Students.objects.count()
        return students

class Maktab(models.Model):
    viloyat = models.ForeignKey(Viloyat, on_delete=models.CASCADE, verbose_name="Viloyat")
    tuman = models.ForeignKey(Tuman, on_delete=models.CASCADE, verbose_name="Tuman")
    title = models.CharField(max_length=100, verbose_name="Maktab")
    creator_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maktab_create", verbose_name="Xodim")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")
    updated = models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active', verbose_name="Holati")
    objects = models.Manager()
    active = ActiveManager()

    def __str__(self):
        return f'{self.title}'
    
    def jami(self):
        return Students.objects.filter(maktab=self.pk).count()

class Students(models.Model):
    viloyat = models.ForeignKey(Viloyat, on_delete=models.CASCADE, verbose_name="Viloyat")
    tuman = models.ForeignKey(Tuman, on_delete=models.CASCADE, verbose_name="Tuman")
    maktab = models.ForeignKey(Maktab, on_delete=models.CASCADE, verbose_name="Maktab")
    sinf = models.CharField(max_length=10, choices=SINF_CHOICES, verbose_name="Sinf")
    fan = models.ForeignKey(Fanlar, on_delete=models.CASCADE, verbose_name="Fan")
    lang = models.CharField(max_length=10, choices=LANG_CHOICES, verbose_name="Til")
    fio = models.CharField(max_length=255, verbose_name="FIO")
    passport = models.CharField(max_length=255, verbose_name="Passport(JSHSHIR)", unique=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")
    updated = models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active', verbose_name="Holati")
    objects = models.Manager()
    active = ActiveManager()

    def __str__(self):
        return f'{self.fio}'

class Natija(models.Model):
    slug = models.UUIDField(default=uuid.uuid4, editable=False)
    fio = models.CharField(max_length=100, verbose_name="Talabaning FIOsi")
    fan = models.CharField(max_length=100, verbose_name="Yo'nalishi")
    urni = models.CharField(max_length=100, verbose_name="Egallagan o'rni")
    ball = models.CharField(max_length=100, verbose_name="To'plagan balli")
    berilgan_vaqt = models.DateTimeField(verbose_name="Berilgan vaqti")
    qr_code = models.ImageField(upload_to='qr_code/%Y/%m/%d/', blank=True)
    diplom = models.ImageField(upload_to='diplom/%Y/%m/%d/', blank=True)
    diplom_seriyasi = models.CharField(max_length=100, verbose_name="Diplom seriyasi")
    sertificate = models.ImageField(upload_to='sertificate/%Y/%m/%d/', blank=True, null=True)
    sertifikat_seriyasi = models.CharField(max_length=100, verbose_name="Sertifikat seriyasi", blank=True, null=True)
    creator_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sert_create", verbose_name="Xodim")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")
    updated = models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='active', verbose_name="Holati")
    objects = models.Manager()
    active = ActiveManager()

    def img(self):
        return mark_safe('\
				<a href="/media/{photo}" target="blank" alt="{name}"> \
					<img src="/media/{photo}" width="50" height="50" /> \
				</a>'.format(
					photo=self.qr_code,
					name=self.fio
				)
			)
    img.short_description = "QR kodi"

    def save(self, *args, **kwargs):
        if not self.qr_code:
            qr = qrcode.QRCode(
                version=9,
                error_correction=qrcode.constants.ERROR_CORRECT_L,
                box_size=10,
                border=4,
            )
            qr.add_data(f'https://olymp.tiu-edu.uz/check/{self.slug}')
            qr.make(fit=True)
            img = qr.make_image(fill_color="black", back_color="white")
            img_io = BytesIO()
            img.save(img_io, 'PNG')
            self.qr_code.save(f'{self.fio}_{self.slug}.jpg', ContentFile(img_io.getvalue()), save=True)
        return super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.fio}'


class Totaldict(models.Model):
    fio = models.CharField(max_length=255, verbose_name="ФИО")
    phone = models.CharField(max_length=255, verbose_name="Телефон")
    email = models.EmailField(verbose_name="Е-маил")
    ish_joyi = models.CharField(max_length=255, verbose_name="Места работы")
    lavozimi = models.CharField(max_length=255, verbose_name="Должность")
    turi = models.CharField(max_length=10, choices=TURI_CHOICES, default='active', verbose_name="Вид")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")
    updated = models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqti")
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='trud', verbose_name="Holati")
    objects = models.Manager()
    active = ActiveManager()

    def __str__(self):
        return f'{self.fio}'

templates/drop_down_maktab.html
<option value="">---------</option>
{% for mak in maktab %}
<option value="{{ mak.pk }}">{{ mak.title }}</option>
{% endfor %}

templates/form.html
{% load static %}
{% load widget_tweaks %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Turan International University</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico'%}">
    <meta name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <!-- Disable tap highlight on IE -->
    <meta name="msapplication-tap-highlight" content="no">

    <link href="{% static 'css.css' %}" rel="stylesheet">
</head>

<body>
    <div class="form-body" style="background: rgba(0,0,0,0.7); ">
        <div class="row">
            <div class="form-holder">
                <div class="form-content">
                    <div class="form-items">
                      {% if vil.first %}
                        <h3>Turan International University</h3>
                        <p>Kerakli bo'limlarni to'ldirib ro'yxatdan o'ting va olimpiada ishtirokchisiga aylaning.</p>
                        <p>Olimpiada 01.04.2023 kuni soat 09:00 da boshlanadi. Manzil: Namangan shaxri, Mamarasulov ko'chasi, 10-d uy.</p>
                        <p>Qo'shimcha ma'lumot uchun tel: +998 88 427 00 55, +998 99 921 00 55</p>
                        
                          {% if messages %}
                            {% for message in messages %}
                            <div class="alert">
                                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                                <strong>{{message}}</strong>
                            </div>
                            {% endfor %}
                          {% endif %}
                          
                          {% if success__ok == True %}
                            <form class="requires-validation" novalidate action="." method="post" id="registerForm" data-maktab-url="{% url 'mainapp:ajax_load_maktab' %}">
                              {% csrf_token %}
                              {{register_form.as_p}}
                              <div style="color: white;">
                                <a id="myBtn" class="btn btn-primary" style="color: black; padding: 5px;">Offerta</a> <span>shartlari bilan tanishib chiqing.</span>
                              </div>
                              
                              <div class="form-button mt-3">
                                <button id="submit" type="submit" class="btn btn-primary" style="cursor: not-allowed; margin-top: 20px;" disabled>Ro'yxatdan o'tish</button>
                              </div>
                            </form>
                            {% else %}
                              <a href="{% url 'mainapp:index' %}" class="btn btn-primary" style="color: black; margin-top: 10px;">Ortga</a>
                          {% endif %}

                          <div id="myModal" class="modal">
                            <div class="modal-content" id="offer">
                              <span class="close">&times;</span>
                                {% include 'nizom.html' %}
                                <div style="margin-top: 20px;">
                                  <input type="checkbox" id="offerid" name="offerid">
                                  <label for="offerid" style="color: #1b00ff"> Offerta bilan tanishib chiqdim va offerta shartlariga roziman.</label>
                                </div>
                              </div>
                          </div>
                        {% else %}
                        <h3>Turan International University</h3>
                        <p>Olimpiada 01.04.2023 kuni soat 09:00 da boshlanadi. Manzil: Namangan shaxri, Mamarasulov ko'chasi, 10-d uy.</p>
                        <p>Qo'shimcha ma'lumot uchun tel: +998 88 427 00 55, +998 99 921 00 55</p>
                          <div class="alert">
                            <!-- <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> -->
                            <strong>Qabul jarayonli yakunlandi.</strong>
                          </div>
                        {% endif %}


                    </div>
                </div>

            </div>
        </div>
    </div>
</body>

<script src="{% static 'jquery-3.3.1.min.js' %}"></script>

<script>
  var modal = document.getElementById("myModal");
  var btn = document.getElementById("myBtn");
  var span = document.getElementsByClassName("close")[0];

  btn.onclick = function() {
    modal.style.display = "block";
  }

  span.onclick = function() {
    modal.style.display = "none";
  }

  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    }
  }
  //  Offerta
  var offer = document.getElementById("offerid");
  var sub = document.getElementById('submit');

  offer.onclick = function() {
    if (sub.disabled == true) 
    {
      sub.disabled = false;
      sub.style.cursor = 'pointer';
    }
    else 
    {
      sub.disabled = true;
      sub.style.cursor = 'not-allowed';
    }
  }

  window.addEventListener('scroll', function() {
      var offerHeight = document.getElementById('offer').offsetHeight;
      var scrolledHeight = window.innerHeight + window.scrollY;
      if (scrolledHeight <= offerHeight) {
          
          console.log(offerHeight);
          console.log('Oxirigacha o\'qidi');
          console.log(scrolledHeight);
      }
  });
</script>

<script>
    $("#id_tuman").change(function () {
      var url = $("#registerForm").attr("data-maktab-url");
      var tumanId = $(this).val();
      $.ajax({
        url: url,
        data: { 'tuman': tumanId },
        success: function (data) {
          $("#id_maktab").html(data);
        }
      });
    });
    $("#id_viloyat").change(function () {
      var url = $("#registerForm").attr("data-maktab-url");
      var viloyatId = $(this).val(); 
      $.ajax({
        url: url,
        data: {
          'viloyat': viloyatId
        },
        success: function (data) {
          $("#id_tuman").html(data);
        }
      });
 
    });
  </script>

</html>

templates/forma_shablon.html
<div class="col-md-4">
                                <div class="valid-feedback">Viloyat tanlang!</div>
                                <select class="form-select mt-3" name="viloyat" required>
                                    <option selected disabled value="">Viloyat</option>
                                    {% for vil in viloyat %}
                                    <option value="{{vil.pk}}">{{vil.title}}</option>
                                    {% endfor %}
                                </select>
                                <!-- <div class="valid-feedback">Viloyat tanlandi!</div> -->
                                <!-- <div class="invalid-feedback">Iltimos viloyatni tanlang!</div> -->
                            </div>
                            <div class="col-md-4">
                                <div class="valid-feedback">Tumanni tanlang!</div>
                                <select class="form-select mt-3" name="tuman" required>
                                    <option selected disabled value="">Tuman</option>
                                    {% for tum in tuman %}
                                    <option value="{{tum.pk}}">{{tum.title}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-md-4">
                                <div class="valid-feedback">Maktabni tanlang!</div>
                                <select class="form-select mt-3" name="maktab" required>
                                    <option selected disabled value="">Maktab</option>
                                    {% for mak in maktab %}
                                    <option value="{{mak.pk}}">{{mak.title}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-md-4">
                                <div class="valid-feedback">Sinfni tanlang!</div>
                                <select class="form-select mt-3" name="sinf" required>
                                    <option selected disabled value="">Sinf</option>
                                    <option value="11-sinf">11-sinf</option>
                                </select>
                            </div>
                            <div class="col-md-4">
                                <div class="valid-feedback">Kerakli fanni tanlang!</div>
                                <select class="form-select mt-3" name="fan" required>
                                    <option selected disabled value="">Fan</option>
                                    {% for fan in fanlar %}
                                    <option value="{{fan.pk}}">{{fan.title}}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-md-4">
                                <div class="valid-feedback">FIO kiriting!</div>
                                <input class="form-control" type="text" name="fio" placeholder="FIO" required>
                            </div>
                            <div class="col-md-4">
                                <div class="valid-feedback">Passport seriya va raqamini kiriting!</div>
                                <input class="form-control" type="text" name="passport"
                                    placeholder="Passport yoki tug'ilganlik haqida guvohnoma" required>
                            </div>

templates/natija.html
{% load static %}
{% load widget_tweaks %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Turan International University</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico'%}">
    <meta name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <!-- Disable tap highlight on IE -->
    <meta name="msapplication-tap-highlight" content="no">

    <link href="{% static 'css.css' %}" rel="stylesheet">
</head>

<body>
    <div class="form-body" style="background: rgba(0,0,0,0.7); ">
        <div class="row">
            <div class="form-holder">
                <div class="form-content">
                    <div class="form-items" >
                    <h3>Turan International University</h3>
                    {% if messages %}
                    {% for message in messages %}
                    <p>Qo'shimcha ma'lumot uchun tel: +998 88 427 00 55, +998 99 921 00 55</p>
                    <div class="alert">
                        <strong>{{message}}</strong>
                    </div>
                    {% endfor %}
                    {% else %}
                    <p>Namangan viloyat XTB bilan hamkorlikda 01.04.2023 kuni o'tkazilgan olimpiada natijasi.</p>
                    <p>Qo'shimcha ma'lumot uchun tel: +998 88 427 00 55, +998 99 921 00 55</p>
                        <table class="table1">
                            <thead>
                                <tr>
                                    <td>T/R</td>
                                    <td>FIO</td>
                                    <td>Fan</td>
                                    <td>Ball</td>
                                    <td>O'rin</td>
                                    <td>Berilgan vaqti</td>
                                    <td>Diplom</td>
                                    <td>Diplom seriyasi</td>
                                    {% if natija.sertificate %}
                                    <td>Sertifikat</td>
                                    <td>Sertifikat seriyasi</td>
                                    {%endif%}
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>1</td>
                                    <td>{{natija.fio}}</td>
                                    <td>{{natija.fan}}</td>
                                    <td>{{natija.ball}}</td>
                                    <td>{{natija.urni}}</td>
                                    <td>{{natija.berilgan_vaqt|date:"d.m.Y"}}</td>
                                    <td><a href="{{natija.diplom.url}}" target="_blank"><img src="{{natija.diplom.url}}" alt="{{natija.fio}}" width="100px"></a></td>
                                    <td>{{natija.diplom_seriyasi}}</td>
                                    {% if natija.sertificate %}
                                        <td><a href="{{natija.sertificate.url}}" target="_blank"><img src="{{natija.sertificate.url}}" alt="{{natija.fio}}" width="100px"></a></td>
                                        <td>{{natija.sertifikat_seriyasi}}</td>
                                    {% endif %}
                                </tr>
                            </tbody>
                        </table>
                        
                        <table class="table2">
                            <tbody>
                                <tr>
                                    <td class="w-10">FIO</td><td class="w-100">{{natija.fio}}</td>
                                </tr>
                                <tr>
                                    <td class="w-10">Fan</td><td class="w-100">{{natija.fan}}</td>
                                </tr>
                                <tr>
                                    <td class="w-10">Ball</td><td class="w-100">{{natija.ball}}</td>
                                </tr>
                                <tr>
                                    <td class="w-10">O'rin</td><td class="w-100">{{natija.urni}}</td>
                                </tr>
                                <tr>
                                    <td class="w-10">Berilgan vaqti</td><td class="w-100">{{natija.berilgan_vaqt|date:"d.m.Y"}}</td>
                                </tr>
                                <tr>
                                    <td class="w-10">Diplom</td><td class="w-100"><a href="{{natija.diplom.url}}" target="_blank"><img src="{{natija.diplom.url}}" alt="{{natija.fio}}" width="100px"></a></td>
                                </tr>
                                <tr>
                                    <td class="w-10">Diplom seriyasi</td><td class="w-100">{{natija.diplom_seriyasi}}</td>
                                </tr>
                                {% if natija.sertificate %}
                                <tr>
                                    <td class="w-10">Sertifikat</td><td class="w-100"><a href="{{natija.sertificate.url}}" target="_blank"><img src="{{natija.sertificate.url}}" alt="{{natija.fio}}" width="100px"></a></td>
                                </tr>
                                <tr>
                                    <td class="w-10">Sertifikat seriyasi</td><td class="w-100">{{natija.sertifikat_seriyasi}}</td>
                                </tr>
                                {%endif%}
                            </tbody>
                        </table>
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

<script src="{% static 'jquery-3.3.1.min.js' %}"></script>

</html>

templates/totaldict.html
{% load static %}
{% load widget_tweaks %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Language" content="en">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Turan International University</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico'%}">
    <meta name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, shrink-to-fit=no" />
    <!-- Disable tap highlight on IE -->
    <meta name="msapplication-tap-highlight" content="no">

    <link href="{% static 'css.css' %}" rel="stylesheet">
</head>

<body>
    <div class="form-body" style="background: rgba(0,0,0,0.7); ">
        <div class="row">
            <div class="form-holder">
                <div class="form-content">
                    <div class="form-items">
                        <h3>Turan International University</h3>
                        <p style="text-align: justify;">Университет «Turan International University» - официальный партнер акции «Тотальный диктант», <br>
                            приглашает всех студентов, старшеклассников, преподавателей,  жителей и гостей города <br>
                            8 апреля 2023 года (13-00)  написать диктант в рамках  акции "Тотальный диктант", <br>
                            а так же принять участие в тестировании TRUD (РКИ).</p>
                        <p>Победителей (лучшая оценка за диктант) ждут приятные поощрения.<br>
                            Адрес: город Наманган, улица Мамарасулова, дом 10-д.</p>
                        <p>Для получения дополнительной информации тел.: +998 88 427 00 55, +998 99 921 00 55</p>
                        
                        {% if vil %}
                          {% if messages %}
                            {% for message in messages %}
                            <div class="alert">
                                <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
                                <strong>{{message}}</strong>
                            </div>
                            {% endfor %}
                          {% endif %}
                          
                          {% if success__ok == True %}
                            <form class="requires-validation" novalidate action="." method="post" id="registerForm">
                              {% csrf_token %}
                              {{register_form.as_p}}
                              
                              <div class="form-button mt-3">
                                <button id="submit" type="submit" class="btn btn-primary" style="margin-top: 20px;">Зарегистрироваться</button>
                              </div>
                            </form>
                            {% else %}
                              <a href="{% url 'mainapp:index' %}" class="btn btn-primary" style="color: black; margin-top: 10px;">Назад</a>
                          {% endif %}

                        {% else %}
                          <div class="alert">
                            <!-- <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> -->
                            <strong>Процесс приема завершен.</strong>
                          </div>
                        {% endif %}


                    </div>
                </div>

            </div>
        </div>
    </div>
</body>


</html>